### ISSUE TITLE
Question: updated gtest?

### ISSUE THREAD

**Issue by GillianGrayson** [end2endzone/cmakeonaplate#1]
Hi!

Very helpful repository! Thank you for sharing!
I think that this is not issue - this is question:
Is it possible to use gtest in the way described here:
https://github.com/google/googletest
under section "Incorporating Into An Existing CMake Project" or in this article:
https://crascit.com/2015/07/25/cmake-gtest/
?

**Comment by end2endzone** [comment]
Hi. Thank you for the feedback.

I am not sure if I understand your question correctly. If I misunderstand your question, I apologize and feel free to correct myself.

The approach described in section [Incorporating Into An Existing CMake Project](https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project) and on [crascit.com](https://crascit.com/2015/07/25/cmake-gtest/) are proposing to integrate `googletest` as part of that your personal project directly. In other words, building gtest **and** the source code of your project together (in the same solution project). As stated in the googletest documentation: "This is a more robust and flexible approach." which is true (in my personal opinion) if your are building an executable or a piece of software that will not be shared/reused in another project. 

I do not personally like this approach and it is not how gtest is expected to be used with `cmakeonaplate`. I prefer to build and install `googletest` from outside of my projects. If I make my template/boilerplate download a version of googletest repository and build gtest as part of its source code it gets quickly complicated if the same template is reused in another project. I build mostly c++ libraries which will be reused eventually in other project.

For instance, let's say library `A` downloads its own copy of gtest and builds it. The project builds fine and is released to the public. Now lets say you start working on library `B` which requires library `A` for building and also defines unit tests. Should library `B` also use the same `ExternalProject_Add()` script and download its own copy of gtest or use the one that will be downloaded by library `A`? Over time the library `B` will add new features and eventually requires linking to library `C` which is also structured like library `A` so it also download its own copy of gtest. It quickly becomes a mess to handle multiple copies of gtest. With this approch, the projects becomes a chain of dependency. I my personal opinion, I think it much easier to build and install each of your dependencies and use [find_package(GTest)](https://github.com/end2endzone/cmakeonaplate/blob/master/library/test/CMakeLists.txt#L3) in your `CMakeLists.txt` file.

**Comment by GillianGrayson** [comment]
Thank you very much for such full explanation!
